# Generated by Django 4.2 on 2023-04-20 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_title_articles_title_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='title_two',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='title_three',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='title_one',
            new_name='title',
        ),
    ]
